kind: Service
apiVersion: v1
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  type: ClusterIP
  selector:
    app: catalogue
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
        version: v1
    spec:
      containers:
      - name: catalogue
        image: catalogue
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
