name: Build catalogue

on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - name: Format check
        run: |
          cd catalogue
          mvn formatter:validate
      - name: Test with Maven
        run: |
          cd catalogue
          mvn test
